### ISSUE TITLE
Pequena melhoria

### ISSUE THREAD

**Issue by PedroW21** [viniciusluzz/Pagina-de-Sorteio#1]
Hey Vinicius, talvez seja uma pequena melhoria que pode fazer no seu projeto, mas a primeira coisa que fiz ao entrar na sua pagina foi so passar o mouse por cima dos icones e acabou que saiu outra descrição kkkkk, segue a print:
.
![image](https://user-images.githubusercontent.com/53663456/189770042-47db6341-556c-4e57-8e03-dfe5376cee0b.png)
![image](https://user-images.githubusercontent.com/53663456/189770076-eb656e21-374b-449f-a6aa-fe0a44085006.png)
![image](https://user-images.githubusercontent.com/53663456/189770113-613a4d23-3a13-4afe-976b-5c03ff39e2d6.png)
.
O de exclamação é intuitivo né, mas os outros eu fiquei meio perdido :D.

**Comment by viniciusluzz** [comment]
Sim cara, eu tentei mudar isso, mas eu peguei esse icone no site ionicons,
via url, e esse nome é atrelado pela tag name na linha de código do ícone.
Resumindo eu achei tão legalzinho que resolvi não mudar, mas muito obrigado
pela dica man!

Em seg., 12 de set. de 2022 19:35, Pedro Verner ***@***.***>
escreveu:

**Comment by PedroW21** [comment]
Ah, kkkkk, blz entao. Nada :D
